# config/services.yaml

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $defaultLocale: 'en'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']

    App\Security\RegistrationHandler:
        arguments:
            $passwordEncoder: '@security.password_encoder'

    App\Service\AuthService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordEncoder: '@security.password_encoder'

    App\Entity\Company:
        autowire: true

    App\Entity\Employee:
        autowire: true

    App\Entity\Project:
        autowire: true

    # Example of injecting parameters
    # App\SomeService:
    #     arguments:
    #         $someParameter: '%some_parameter%'

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class

    # add more services here that are needed for the project
